### POST request to create a new patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Pramod Bharti Kafka",
  "email": "kafka-test@example.com",
  "address": "123, India",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-09-09"
}

###