### POST request to create a new patient
POST http://lb-ce57bee5.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pramod Bharti",
  "email": "ecs-test@example.com",
  "address": "123, India",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-09-09"
}

###