spring.application.name=appointment-service
server.port=4006
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://appointment-service-db:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}